# Generated by Django 4.1.1 on 2023-04-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('ac', models.BooleanField(default=True)),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol')], default='Diesel', max_length=20)),
                ('seats', models.SmallIntegerField(default=4)),
                ('popular', models.BooleanField(default=False)),
                ('cat', models.CharField(choices=[('Sedan Cabs', 'Sedan Cabs'), ('MUV Cabs', 'MUV Cabs'), ('SUV Cabs', 'SUV Cabs'), ('Minibus Cabs', 'Minibus Cabs'), ('Rental Vehicles', 'Rental Vehicles'), ('Rental Bikes', 'Rental Bikes')], default='Rental Vehicles', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Location')),
                ('img', models.ImageField(upload_to='')),
                ('to_be_shown', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inclusions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Popular_Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('main_img', models.ImageField(upload_to='')),
                ('front_img', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('starting_from', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('days', models.SmallIntegerField(default=3)),
                ('nights', models.SmallIntegerField(default=3)),
                ('front_img', models.ImageField(default='default.jpg', null=True, upload_to='')),
                ('main_img', models.ImageField(default='default.jpg', upload_to='')),
                ('category', models.CharField(max_length=100, null=True)),
                ('volvo', models.BooleanField(default=False)),
                ('top_package', models.BooleanField(default=False)),
                ('cities', models.ManyToManyField(to='website.popular_destination')),
            ],
        ),
        migrations.CreateModel(
            name='Pack_Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(default=None, null=True)),
                ('img', models.URLField(null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.package')),
            ],
        ),
    ]
